export const browserCoreExamples = [
  "jar4 browser status",
  "jar4 browser start",
  "jar4 browser stop",
  "jar4 browser tabs",
  "jar4 browser open https://example.com",
  "jar4 browser focus abcd1234",
  "jar4 browser close abcd1234",
  "jar4 browser screenshot",
  "jar4 browser screenshot --full-page",
  "jar4 browser screenshot --ref 12",
  "jar4 browser snapshot",
  "jar4 browser snapshot --format aria --limit 200",
  "jar4 browser snapshot --efficient",
  "jar4 browser snapshot --labels",
];

export const browserActionExamples = [
  "jar4 browser navigate https://example.com",
  "jar4 browser resize 1280 720",
  "jar4 browser click 12 --double",
  'jar4 browser type 23 "hello" --submit',
  "jar4 browser press Enter",
  "jar4 browser hover 44",
  "jar4 browser drag 10 11",
  "jar4 browser select 9 OptionA OptionB",
  "jar4 browser upload /tmp/file.pdf",
  'jar4 browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "jar4 browser dialog --accept",
  'jar4 browser wait --text "Done"',
  "jar4 browser evaluate --fn '(el) => el.textContent' --ref 7",
  "jar4 browser console --level error",
  "jar4 browser pdf",
];
